import { config } from "dotenv";
import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

config();

let modoDesarrollo = process.env.DEVMODE == "true";

export const metadata: Metadata = {
  title: "Prometeus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <h1>Prometeus</h1>
          </header>
          {modoDesarrollo
            ? [
                children,
                <script src="axe.min.js"></script>,
                <script src="main.js"></script>,
              ]
            : children}
        </body>
      </html>
    </ClerkProvider>
  );
}
