import { config } from 'dotenv'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

config();

let modoDesarrollo = process.env.DEVMODE == "true";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Prometeus',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{
        (modoDesarrollo)?[children, <script src="axe.min.js"></script>, <script src="main.js"></script>]:children
      }</body>
    </html>
  )
}
